spring:
  application:
    name: api.registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: true
    fetchRegistry: false