version: '3'

services:
  postgres-compose:
    image: postgres
    container_name: postgre_api_db
    environment:
      POSTGRES_DB: "db_twitter"
      POSTGRES_USER: "twitter"
      POSTGRES_PASSWORD: "Postgres2019!"
    expose:
      - "5432"
    networks:
      - compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: postgre_api_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "gustavopomponi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "gustavopomponi@gmail.com"
    ports:
      - "18543:80"
    depends_on:
      - postgres-compose
    networks:
      - compose-network

  api-twitter-service:
    image: gustavopomponi/pomponi-hub:scg-api-twitter-posts
    container_name: api-twitter-posts
    depends_on:
      - postgres-compose
      - api-registry
    environment:
      PG_HOST: postgres-compose
      PG_PORT: 5432
      PG_USERNAME: twitter
      PG_DATABASE: db_twitter
      PG_PASSWORD: Postgres2019!
    expose:
      - "8083"
    networks:
      - compose-network

  api-gateway:
    image: gustavopomponi/pomponi-hub:scg-api-gateway
    container_name: api-gateway
    environment:
      APITWITTER_HOST: api-twitter-service
      APITWITTER_PORT: 8083
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - api-twitter-service
      - api-authentication
      - api-registry
    networks:
      - compose-network
    links:
      - api-registry

  api-authentication:
    image: gustavopomponi/pomponi-hub:scg-api-authentication
    container_name: api-authentication
    expose:
      - "8090"
    ports:
      - "8090:8090"
    networks:
      - compose-network

  api-registry:
    image: gustavopomponi/pomponi-hub:scg-api-registry
    container_name: api-registry
    environment:
      REGISTRY_HOST: api-registry
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - compose-network

networks: 
  compose-network:
    driver: bridge
